<?php
// database/seeders/ArticleSeeder.php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        $boissons = Category::query()->where('slug', 'boissons')->firstOrFail();
        $alimentation = Category::query()->where('slug', 'alimentation')->firstOrFail();
        $laitiers = Category::query()->where('slug', 'produits-laitiers')->firstOrFail();
        $hygiene = Category::query()->where('slug', 'hygiene-beaute')->firstOrFail();
        $menagers = Category::query()->where('slug', 'articles-menagers')->firstOrFail();

        $articles = [
            [
                'category_id' => $boissons->id,
                'name' => 'Eau minerale 50cl',
                'sku' => 'EAU-50CL-001',
                'barcode' => '1234567890123',
                'description' => 'Eau minerale naturelle, bouteille 50cl',
                'price' => 5000,
                'cost_price' => 3500,
                'unit_type' => 'PACK',
                'units_per_pack' => 24,
                'unit_price' => 250,
                'initial_quantity' => 50,
                'current_stock' => 50,
                'alert_threshold' => 10,
                'expiration_date' => now()->addYear(),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $boissons->id,
                'name' => "Jus d'orange 1L",
                'sku' => 'JUS-ORA-001',
                'barcode' => '1234567890124',
                'description' => "Jus d'orange 100% pur fruit presse",
                'price' => 12000,
                'cost_price' => 8500,
                'unit_type' => 'PACK',
                'units_per_pack' => 12,
                'unit_price' => 1100,
                'initial_quantity' => 30,
                'current_stock' => 30,
                'alert_threshold' => 5,
                'expiration_date' => now()->addMonths(6),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $alimentation->id,
                'name' => 'Riz importe 25kg',
                'sku' => 'RIZ-25KG-001',
                'barcode' => '1234567890125',
                'description' => 'Riz blanc importe, sac de 25kg',
                'price' => 45000,
                'cost_price' => 38000,
                'unit_type' => 'UNIT',
                'units_per_pack' => null,
                'unit_price' => null,
                'initial_quantity' => 100,
                'current_stock' => 100,
                'alert_threshold' => 20,
                'expiration_date' => now()->addYears(2),
                'is_active' => true,
                'allow_unit_sale' => false,
            ],
            [
                'category_id' => $alimentation->id,
                'name' => 'Huile vegetale 5L',
                'sku' => 'HUI-5L-001',
                'barcode' => '1234567890126',
                'description' => 'Huile de palme raffinee, bidon 5 litres',
                'price' => 28000,
                'cost_price' => 22000,
                'unit_type' => 'UNIT',
                'units_per_pack' => null,
                'unit_price' => null,
                'initial_quantity' => 60,
                'current_stock' => 60,
                'alert_threshold' => 15,
                'expiration_date' => now()->addYear(),
                'is_active' => true,
                'allow_unit_sale' => false,
            ],
            [
                'category_id' => $alimentation->id,
                'name' => 'Sucre en poudre 1kg',
                'sku' => 'SUC-1KG-001',
                'barcode' => '1234567890127',
                'description' => 'Sucre blanc en poudre, sachet 1kg',
                'price' => 3500,
                'cost_price' => 2800,
                'unit_type' => 'PACK',
                'units_per_pack' => 10,
                'unit_price' => 400,
                'initial_quantity' => 80,
                'current_stock' => 80,
                'alert_threshold' => 20,
                'expiration_date' => now()->addYears(3),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $laitiers->id,
                'name' => 'Lait frais 1L',
                'sku' => 'LAIT-1L-001',
                'barcode' => '1234567890128',
                'description' => 'Lait entier UHT, brique 1 litre',
                'price' => 4500,
                'cost_price' => 3200,
                'unit_type' => 'PACK',
                'units_per_pack' => 12,
                'unit_price' => 450,
                'initial_quantity' => 40,
                'current_stock' => 40,
                'alert_threshold' => 10,
                'expiration_date' => now()->addMonths(8),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $laitiers->id,
                'name' => 'Yaourt nature 125g',
                'sku' => 'YAU-125G-001',
                'barcode' => '1234567890129',
                'description' => 'Yaourt nature, pot individuel 125g',
                'price' => 8000,
                'cost_price' => 5500,
                'unit_type' => 'PACK',
                'units_per_pack' => 8,
                'unit_price' => 1100,
                'initial_quantity' => 25,
                'current_stock' => 25,
                'alert_threshold' => 8,
                'expiration_date' => now()->addDays(21),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $hygiene->id,
                'name' => 'Savon de toilette 200g',
                'sku' => 'SAV-200G-001',
                'barcode' => '1234567890130',
                'description' => 'Savon parfume, pain de 200g',
                'price' => 6000,
                'cost_price' => 4200,
                'unit_type' => 'PACK',
                'units_per_pack' => 6,
                'unit_price' => 1200,
                'initial_quantity' => 45,
                'current_stock' => 45,
                'alert_threshold' => 12,
                'expiration_date' => now()->addYears(2),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $hygiene->id,
                'name' => 'Dentifrice 100ml',
                'sku' => 'DEN-100ML-001',
                'barcode' => '1234567890131',
                'description' => 'Dentifrice blancheur, tube 100ml',
                'price' => 5500,
                'cost_price' => 3800,
                'unit_type' => 'PACK',
                'units_per_pack' => 12,
                'unit_price' => 550,
                'initial_quantity' => 35,
                'current_stock' => 35,
                'alert_threshold' => 10,
                'expiration_date' => now()->addYears(3),
                'is_active' => true,
                'allow_unit_sale' => true,
            ],
            [
                'category_id' => $menagers->id,
                'name' => 'Lessive liquide 2L',
                'sku' => 'LES-2L-001',
                'barcode' => '1234567890132',
                'description' => 'Lessive liquide concentree, bidon 2 litres',
                'price' => 15000,
                'cost_price' => 10500,
                'unit_type' => 'UNIT',
                'units_per_pack' => null,
                'unit_price' => null,
                'initial_quantity' => 30,
                'current_stock' => 30,
                'alert_threshold' => 8,
                'expiration_date' => now()->addYears(2),
                'is_active' => true,
                'allow_unit_sale' => false,
            ],
        ];

        foreach ($articles as $article) {
            Article::query()->firstOrCreate(
                ['sku' => $article['sku']],
                $article,
            );
        }
    }
}
